name: 'markdown-to-supabase'
description: 'A Github action which syncs your markdown files with your Supabase database'
author: 'Johnny Magrippis'
branding:
  icon: 'database'
  color: 'green'

# Define your inputs here.
inputs:
  docs-root-path:
    description:
      'The path to the root of your docs directory, which has all the markdown
      files you would like to sync with your DB'
    required: false
    default: 'docs'
  target-table:
    description: 'The target table in your Supabase DB. All the matching markdown files will be synced there!'
    required: false
    default: 'docs'
  supabase-url:
    required: true
    description: 'Your Supabase project URL'
  supabase-service-role-key:
    required: true
    description: 'Your Supabase SERVICE_ROLE key'

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: cd ${{ github.action_path }}
      shell: bash
    - run: bun install --production
      shell: bash
    - run: bun src/index.ts
      shell: bash
      env:
        DOCS_ROOT_PATH: ${{ inputs.docs-root-path }}
        TARGET_TABLE: ${{ inputs.target-table }}
        PUBLIC_SUPABASE_URL: ${{ inputs.supabase-url }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ inputs.supabase-service-role-key }}
